platform :ios, '7.0'
pod 'AFNetworking', '~> 2.6.1'
pod 'Mantle', '~> 2.0'
pod 'BFKit', '~> 1.8.0'
pod 'BlocksKit', '~> 2.2'
pod 'FMDB', '~>2.5'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'IQKeyboardManager', '~> 3.3'
pod 'QRCodeReaderViewController', '~> 4.0.1'
pod 'MJRefresh', '~> 2.4.12'
pod 'Masonry', '~> 0.6.4'